%{?scl:%scl_package nodejs-once}
%{!?scl:%global pkg_name %{name}}
%{?nodejs_find_provides_and_requires}

Name:           %{?scl_prefix}nodejs-once
Version:        1.3.3
Release:        2%{?dist}
Summary:        Run a function exactly one time
BuildArch:      noarch
ExclusiveArch:  %{nodejs_arches} noarch
License:        ISC
URL:            https://github.com/isaacs/once
Source0:        http://registry.npmjs.org/once/-/once-%{version}.tgz

BuildRequires:  %{?scl_prefix}nodejs-devel

%description
Run a function exactly one time.

%prep
%setup -q -n package

%build
#nothing to do

%install
mkdir -p %{buildroot}%{nodejs_sitelib}/once
cp -pr package.json once.js %{buildroot}%{nodejs_sitelib}/once

%nodejs_symlink_deps

%files
%{nodejs_sitelib}/once
%doc LICENSE README.md

%changelog
* Thu Jun 09 2016 Zuzana Svetlikova <zsvetlik@redhat.com> - 1.3.3-2
- Resolves: rhbz#1334856 , fixes wrong license

* Sun Feb 14 2016 Zuzana Svetlikova <zsvetlik@redhat.com> - 1.3.1-1
- Update

* Thu Jan 16 2014 Tomas Hrcka <thrcka@redhat.com> - 1.3.0-1
- New upstream release 1.3.0

* Thu Oct 17 2013 Tomas Hrcka <thrcka@redhat.com> - 1.1.1-5
- replace provides and requires with macro

* Thu Apr 11 2013 Stanislav Ochotnicky <sochotnicky@redhat.com> - 1.1.1-4
- Add support for software collections

* Thu Feb 14 2013 Fedora Release Engineering <rel-eng@lists.fedoraproject.org> - 1.1.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_19_Mass_Rebuild

* Tue Jan 08 2013 T.C. Hollingsworth <tchollingsworth@gmail.com> - 1.1.1-2
- add missing build section
- sentences end with a period

* Mon Dec 31 2012 T.C. Hollingsworth <tchollingsworth@gmail.com> - 1.1.1-1
- initial package generated by npm2rpm
